apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo-service 27017; do echo "Waiting for database..."; sleep 2; done;']
      containers:
        - name: nodejs
          image: docker.io/thecodegirl/nodejs_wait:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: nodejs-config
            - secretRef:
                name: mongo-secrets
          volumeMounts:
            - mountPath: /home/node/app
              name: node-volume
            - mountPath: /home/node/app/node_modules
              name: node-modules
          command: ["/bin/sh", "-c", "npm start"]
      imagePullSecrets:
        - name: my-registry-key
      volumes:
        - name: node-volume
          hostPath:
            path: "/home/ubuntu/node_project/nodeproject" # Adjust the path to your project folder
            type: DirectoryOrCreate
        - name: node-modules
          persistentVolumeClaim:
            claimName: node-modules-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
